### ISSUE TITLE
Add multisensor grouping capability

### ISSUE THREAD

**Issue by tnyeUSGS** [usgs/shakemap-amp-tools#106]
Example scenario. There is a building with multiple sensors. The station name, start time, and orientations of the sensors are the same. At this time, these sensor traces will be marked as duplicates.
[891018_1.cra-1.0254i.txt](https://github.com/usgs/shakemap-amp-tools/files/2267424/891018_1.cra-1.0254i.txt)
[891018_1.cra-1.0254a.txt](https://github.com/usgs/shakemap-amp-tools/files/2267425/891018_1.cra-1.0254a.txt)

**Comment by tnyeUSGS** [comment]
For SMC format. Use floor and building type integers 19 and 25.

**Comment by mhearne-usgs** [comment]
For COSMOS, use sensor number as location code (01-99), and then add a location kwarg for read_smc and force the user to figure out what the location for the given file should be. Look into any identifying info in the other engineering formats (USC, DMG, etc.) to see if anything can be used.
