### ISSUE TITLE
Restrict structure types in COSMOS files to 1-4 from Table 6

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap-amp-tools#11]
We don't want strong motion data from multi-story buildings, for example.

In the long term, we'll want this to be configurable, but we need to figure out how to handle that for the package.

**Comment by hschovanec-usgs** [comment]
Structure types can be limited using the parameter *valid_station_types*. 
Example: `stream = read_cosmos(filename, valid_station_types=[1, 2, 3, 4])`
