### ISSUE TITLE
Create tool to download ShakeMap input data from INGV

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap-amp-tools#114]
Create a tool that uses EMSC ID web service and INGV Strong Motion web service:

http://www.seismicportal.eu/eventid/

http://webservices.ingv.it/swagger-ui/dist/?url=http%3A%2F%2Fwebservices.ingv.it%2Fingvws%2Fstrongmotion%2F1%2Fswagger.yml

**Comment by hschovanec-usgs** [comment]
closed by #119
