### ISSUE TITLE
smconvert and fdsnfetch not available in amptools environment after automated install

### ISSUE THREAD

**Issue by ewolin-usgs** [usgs/shakemap-amp-tools#117]
I installed amptools following the "automated install" instructions on the readme:
```
git clone https://github.com/usgs/shakemap-amp-tools.git
cd shakemap-amp-tools
bash install.sh
conda activate amptools
```
After a successful installation and activating the amptools environment, smconvert and fdsnfetch are not installed in $HOME/anaconda3/envs/amptools/bin.  The other 3 scripts in the bin directory (amps2xml, ftpfetch, sm2xml) are placed there.
I can run fdsnfetch by calling it from the directory where I cloned the git repository, for example:
`$HOME/code/shakemap-amp-tools/bin/fdsnfetch data-with-amptools IRIS 2018-05-04T22:32:56 19.370 -155.032 -n HV -s JOKA -c '?N?' -f 'MSEED'`
but of course it'd be nice if everything got installed in the amptools bin directory.

**Comment by mhearne-usgs** [comment]
Its probably much easier to use the conda install procedure:

conda config --add channels conda-forge
conda install amptools

Try that and report back if it doesn't work.

@hschovanec-usgs We should add that conda config line to the README.

**Comment by emthompson-usgs** [comment]
Is there any reason to keep the install.sh file for this repository if it can be installed via conda-forge?

**Comment by mhearne-usgs** [comment]
It's useful for developers, so I would say yes.

**Comment by ewolin-usgs** [comment]
Ok, I tried creating a new conda environment and installing via conda-forge:
```
conda create -n amptoolsconda
conda activate amptoolsconda
conda install amptools
```
and I have the same results: 
amps2xml, ftpfetch, sm2xml all end up in $HOME/anaconda3/envs/amptoolsconda/bin and can be found with which, but smconvert and fdsnfetch still aren't there.

**Comment by emthompson-usgs** [comment]
This appears to be resolved.
