### ISSUE TITLE
Remove extraneous if statements from streams.py

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap-amp-tools#59]
In streams_to_dataframe, there are now a bunch of extraneous checks for old metadata - these should now be safe to remove.

**Comment by hschovanec-usgs** [comment]
This issue depends on completion of #24

**Comment by mhearne-usgs** [comment]
https://github.com/usgs/shakemap-amp-tools/blob/master/amptools/stream.py#L238
