### ISSUE TITLE
Signal-to-noise ratio

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap-amp-tools#95]
Be sure that the code is aware that the what we sometimes call the "signal" window is actually "signal and noise" window or the "total" window. So the signal to noise ratio is actually calculated as 
```
(total - noise)/noise
```

**Comment by jrekoske-usgs** [comment]
I believe this should already be accounted for in the get_corner_frequencies function. The Rennolet paper states: "We removed the noise level from the spectrum of the signal window to estimate the signal spectrum."

This implementation of this statement is line 259 of process.py

`# remove the noise level from the spectrum of the signal window`
`sig_spec_smooth -= noise_spec_smooth`

**Comment by emthompson-usgs** [comment]
Ok, perfect. Closing the issue now.
